# Path to your KO-HMM database
# A database can be a .hmm file, a .hal file or a directory in which
# .hmm files are. Omit the extension if it is .hal or .hmm file
profile: /kofam_scan/profiles

# Path to the KO list file
ko_list: /kofam_scan/ko_list

# Path to an executable file of hmmsearch
# You do not have to set this if it is in your $PATH
hmmsearch: /opt/conda/bin/hmmsearch

# Path to an executable file of GNU parallel
# You do not have to set this if it is in your $PATH
parallel: /usr/bin/parallel

# Number of hmmsearch processes to be run parallelly
cpu: 2
